```python
import pandas as pd
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import os
from datetime import datetime

# CONFIGURATION
INPUT_FOLDER = './field_data'
OUTPUT_FOLDER = './generated_reports'
AUTHOR = "Dyami Connell"

def create_report(input_file, output_pdf):
    """
    Reads an HVAC Field Report (Excel) and generates a PDF summary.
    """
    try:
        # Read the Excel file using pandas
        df = pd.read_excel(input_file)
        
        # Initialize PDF
        c = canvas.Canvas(output_pdf, pagesize=letter)
        width, height = letter
        
        # Header Information
        c.setFont("Helvetica-Bold", 16)
        c.drawString(50, height - 50, "HVAC TAB Field Report")
        
        c.setFont("Helvetica", 10)
        c.drawString(50, height - 70, f"Generated by: {AUTHOR}")
        c.drawString(50, height - 85, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        
        # Draw Data Table from Excel
        y_position = height - 120
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, y_position, "Traverse Data Summary:")
        
        y_position -= 20
        c.setFont("Courier", 10)
        
        # Iterate through rows in the Excel sheet
        for index, row in df.iterrows():
            if y_position < 50:
                c.showPage() # Create new page if full
                y_position = height - 50
            
            # Format: System ID | Design CFM | Actual CFM
            line_text = f"Unit: {row.get('UnitID', 'N/A')} | Design: {row.get('Design_CFM', 0)} | Actual: {row.get('Actual_CFM', 0)}"
            c.drawString(50, y_position, line_text)
            y_position -= 15
            
        c.save()
        print(f"Success: Generated report for {input_file}")
        
    except Exception as e:
        print(f"Error processing {input_file}: {e}")

def main():
    """
    Main execution loop. Scans directory for Excel files and processes them.
    """
    if not os.path.exists(OUTPUT_FOLDER):
        os.makedirs(OUTPUT_FOLDER)
        
    print(f"Starting TAB Report Automation - developed by {AUTHOR}")
    
    # Mock loop for demonstration purposes
    # In a real scenario, this would iterate through os.listdir(INPUT_FOLDER)
    print("Waiting for input files...")

if __name__ == "__main__":
    main()
